name: Zipping

on: [workflow_dispatch]

jobs:
    build:
        name: Creating releases
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install zip
              run: sudo apt-get install zip

            - name: Zip code
              run: zip -r code.zip .

            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::$(date +'%Y%m%d%H%M%S')

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.get_version.outputs.VERSION }}
                  release_name: Release ${{ steps.get_version.outputs.VERSION }}
                  body: Description for this release
                  draft: false
                  prerelease: false

            - name: Upload Release Asset
              id: upload_release_asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./code.zip
                  asset_name: code.zip
                  asset_content_type: application/zip
